<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Dependency;

class DependencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Dependency::insert([
            [
                "id" => 1,
                "dependency_name" => "Orquesta Sinfónica de El Salvador",
                "address" => "Colonia San Benito, final Av. La Revolución. ",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 2,
                "dependency_name" => "Unidad de Talento Humano",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Segundo Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 3,
                "dependency_name" => "Centro Nacional de Artes",
                "address" => "Calle Valero Lecha Edificio CENAR, Colonia San Mateo",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 4,
                "dependency_name" => "Parque Infantil de Diversiones",
                "address" => "3a. Av. Nte. y Alameda Juan Pablo II.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 5,
                "dependency_name" => "Museo Nacional de Antropología Dr. David J. Guzmán",
                "address" => "Av. La Revolución, Col. San Benito. Museo Nacional de Antropología Dr. David J. Guzmán",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 6,
                "dependency_name" => "Unidad de Activo Fijo",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Primer Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 7,
                "dependency_name" => "Biblioteca Nacional de El Salvador Francisco Gavidia",
                "address" => "4a. Calle oriente y Av. Monseñor Oscar A. Romero No. 124.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 8,
                "dependency_name" => "Coordinación Departamental de Cuscatlán",
                "address" => "Av. José María Rivas, Nº 15 Barrio Concepción, Cojutepeque. ",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 9,
                "dependency_name" => "Unidad de Informática y Sistemas",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Tercer Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 10,
                "dependency_name" => "Parque Arqueológico Casa Blanca",
                "address" => "Km. 78, sobre la carretera de Santa Ana a Chalchuapa. ",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 11,
                "dependency_name" => "Teatro Nacional de San Salvador",
                "address" => "Avenida Monseñor Romero y Calle Delgado Frente a Plaza Morazán, Centro Histórico.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 12,
                "dependency_name" => "Biblioteca Pública Prof. Saúl Flores",
                "address" => "Dr. Nicolás Peña No. 43, Barrio Candelaria, Zacatecoluca",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 13,
                "dependency_name" => "Museo de Historia Natural de El Salvador",
                "address" => "Final Calle Los Viveros Col. Nicaragua",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 14,
                "dependency_name" => "Unidad de Adquisiciones y Contrataciones Institucional",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Primer Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 15,
                "dependency_name" => "Sistema de Coros y Orquestas Juveniles de El Salvador",
                "address" => "19 Avenida Norte, contiguo a Colegio La Asunción, frente a Facultad de Veterinaria de la Universidad Alberto Masferrer.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 16,
                "dependency_name" => "Biblioteca Pública Prof. Juana Castro de Serrano",
                "address" => "3a. Calle Poniente, Casa No. 5, Barrio Mercedes, San Martín.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 17,
                "dependency_name" => "Parque Zoológico Nacional",
                "address" => "Final Barrio Modelo",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 18,
                "dependency_name" => "Despacho Ministerio de Cultura",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Tercer Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 19,
                "dependency_name" => "Parque Arqueológico Joya de Cerén ",
                "address" => "Parque Arqueológico Joya de Cerén, Km. 35 1/2 carretera hacia San Juan Opico, Municipio San Juan Opico,",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 20,
                "dependency_name" => "Teatro Nacional de Santa Ana",
                "address" => "2a Calle Poniente y Avenida Independencia Norte, Centro Histórico",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 21,
                "dependency_name" => "Coordinación Departamental de La Paz",
                "address" => "2a. Calle Pte. Nº 1 Barrio El Centro, Zacatecoluca. ",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 22,
                "dependency_name" => "Ballet Folklórico Nacional",
                "address" => "6a Av. Norte No. 319, Barrio San José.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 23,
                "dependency_name" => "Unidad de Gestión Documental y Archivos",
                "address" => "Final Calle México y 2a Av Sur, Barrio San Jacinto, Ex - Casa Presidencial.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 24,
                "dependency_name" => "Atención al Cliente",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 25,
                "dependency_name" => "Biblioteca Nacional Francisco Gavidia",
                "address" => "Biblioteca Nacional Francisco Gavidia,  Av. Monseñor Romero y 4a. Calle Ote. No. 124",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 26,
                "dependency_name" => "Ballet Nacional",
                "address" => "75 Av. Sur, Pasaje C, Casa 4 A, Colonia Escalón,",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 27,
                "dependency_name" => "Casa del Escritor",
                "address" => "Planes de Renderos",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 28,
                "dependency_name" => "Casa de la Cultura de Ayutuxtepeque",
                "address" => "1a Calle Pte. No. 1 Anexo a la Alcaldía Municipal. Ayutuxtepeque",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 29,
                "dependency_name" => "Casa de la Cultura de El Centro",
                "address" => "8a Avenida Norte # 228, Centro Histórico, ",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 30,
                "dependency_name" => "Sitio Arqueológico Joya de Cerén",
                "address" => "Carretera a San Juan Opico, Agua Escondida Km. 32",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 31,
                "dependency_name" => "Coordinación Departamental de Usulután ",
                "address" => "Av. Teniente Coronel Gerson Calito, Centro de Gobierno, Usulután ",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 32,
                "dependency_name" => "Compañía Nacional de Danza",
                "address" => "75 Av. Sur, Pasaje C, Casa 4 A, Colonia Escalón, ",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 33,
                "dependency_name" => "Comité de Eficiencia Energética - Oficinas Centrales",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Segundo Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 34,
                "dependency_name" => "Comité de Seguridad - Oficinas Centrales",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Primer Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 35,
                "dependency_name" => "Unidad de Logística",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Primer Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 36,
                "dependency_name" => "Ministerio de Cultura",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 37,
                "dependency_name" => "Archivo General de la Nación",
                "address" => "Palacio Nacional, Av. Cuscatlán y 4a Calle Oriente, Centro Histórico.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 38,
                "dependency_name" => "Unidad de Acceso a la Información Pública",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Segundo Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 39,
                "dependency_name" => "Unidad Financiera Institucional",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Primer Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 40,
                "dependency_name" => "Departamento de Cine y Audiovisuales",
                "address" => "Av. La Revolución, Col. San Benito. Museo Nacional de Antropología Dr. David J. Guzmán",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 41,
                "dependency_name" => "Escuela Nacional de Danza",
                "address" => "1a Calle Poniente, Nº 1233.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 42,
                "dependency_name" => "Sala de Exposiciones San Jacinto",
                "address" => "Final Calle México y 10a Av Sur, Barrio San Jacinto, Ex - Casa Presidencial.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 43,
                "dependency_name" => "Coro Patrimonial de El Salvador",
                "address" => "Avenida La Revolución, Col. San Benito, Museo Nacional de Antropología Dr. David J. Guzmán",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 44,
                "dependency_name" => "Palacio Nacional",
                "address" => "Palacio Nacional, Centro Histórico",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 45,
                "dependency_name" => "Teatro Presidente",
                "address" => "Colonia San Benito, final Av. La Revolución.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 46,
                "dependency_name" => "Unidad de Mantenimiento",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Primer Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 47,
                "dependency_name" => "Museo Regional de Occidente",
                "address" => "Avenida Independencia sur N.º 8.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 48,
                "dependency_name" => "Coro Nacional de El Salvador",
                "address" => "8a. Avenida Norte, No. 228.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 49,
                "dependency_name" => "Biblioteca Pública Antonio Blandón Ramírez",
                "address" => "Pasaje Cruz Roja, frente al Estadio Sergio Torres, No. 3. Usulután.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 50,
                "dependency_name" => "Biblioteca Pública Chapultepec",
                "address" => "8a. Avenida Norte No. 228.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 51,
                "dependency_name" => "Gestión",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 52,
                "dependency_name" => "Biblioteca Pública de San Miguel",
                "address" => "11 Av. Norte No. 605, Barrio San Francisco.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 53,
                "dependency_name" => "Escuela Nacional de Danza Morena Celarié",
                "address" => "1a. Calle Poniente, No. 1233.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 54,
                "dependency_name" => "Coordinación Departamental de San Vicente ",
                "address" => "Barrio El Centro, Calle Principal, Nº S/N contiguo a Alcaldía Municipal, Santo Domingo.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 55,
                "dependency_name" => "Teatro Nacional de San Miguel",
                "address" => "2a Calle Ote. y 6a Avenida Nte., Barrio La Cruz.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 56,
                "dependency_name" => "Departamental de Casas de la Cultura, San Salvador",
                "address" => "8a Avenida Norte # 228, Centro Histórico,",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 57,
                "dependency_name" => "Sala Nacional de Exposiciones Salarrué",
                "address" => "6a10a Calle y 25 Av. Sur, Parque Cuscatlán.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 58,
                "dependency_name" => "Externo",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 59,
                "dependency_name" => "Programa de Transferencia de Recursos",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Primer Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 60,
                "dependency_name" => "Biblioteca Pública de Nuevo Gualcho",
                "address" => "Cantón Azacualpía, Nuevo Gualcho.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 61,
                "dependency_name" => "Biblioteca Pública Alfredo Espino Ahuachapán",
                "address" => "2a. Avenida Norte, No. 1-4 Bo. El Centro. ",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 62,
                "dependency_name" => "Coordinación Departamental de Morazán",
                "address" => "Final calle Joaquin Rodezno y 3a. Ave. Norte, No.1, Barrios Las Flores, San Francisco Gotera, Morazán",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 63,
                "dependency_name" => "Despacho del Viceministro",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Tercer Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 64,
                "dependency_name" => "Parque Arqueológico Tazumal",
                "address" => "Parque Arqueológico Tazumal, diagonal 5a. Calle Ote. Calle al Cuje, Chalchuapa",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 65,
                "dependency_name" => "Coordinación Departamental de Sonsonate ",
                "address" => "Calle Alberto Masferrer y Av. Morazán,",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 66,
                "dependency_name" => "Biblioteca Pública David Granadino",
                "address" => "Calle Libertad Poniente, entre 6a. y 8a. Av. Sur.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 67,
                "dependency_name" => "Museo Regional de Oriente",
                "address" => "8a. Av. Sur y 15 Calle Oriente, Local B Centro de Gobierno Departamental",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 68,
                "dependency_name" => "Red de Bibliotecas",
                "address" => "8a. Avenida Norte No.228,",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 69,
                "dependency_name" => "Coordinación Departamental de La Unión ",
                "address" => "5a Av. Nte. Nº 2-6 Barrio Concepción, La Unión ",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 70,
                "dependency_name" => "Casa de la Cultura de San Jacinto",
                "address" => "Final Calle México y 2a Av Sur, Barrio San Jacinto, Ex - Casa Presidencial.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 71,
                "dependency_name" => "Parque Zoologico Nacional",
                "address" => "Final Barrio Modelo",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 72,
                "dependency_name" => "Parque Saburo Hirao",
                "address" => "Final Calle Los Viveros, Colonia Nicaragua. ",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 73,
                "dependency_name" => "Coordinación Departamental de Cabañas",
                "address" => "Av. Carlos Bonilla y 5a. Calle Pte Nº 1 Barrio San Sebastián, Ilobasco, Cabañas. ",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 74,
                "dependency_name" => "Red de Bibliotecas Públicas",
                "address" => "Biblioteca Nacional Francisco Gavidia, Av. Monseñor Romero y 4a. Calle Ote. No. 124",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 75,
                "dependency_name" => "Biblioteca Pública de Chalatenango ",
                "address" => "1a. Av. Norte, Barrio San José.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 76,
                "dependency_name" => "Sitio Arqueológico San Andrés",
                "address" => "Km. 32 Carretera Panamericana en el sentido que conduce al Occidente, Ciudad Arce.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 77,
                "dependency_name" => "Red de Casas de la Cultura",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Segundo Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 78,
                "dependency_name" => "Unidad de Adquisiciones y Contrataciones Institucionales",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Primer Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 79,
                "dependency_name" => " Unidad Financiera Institucional",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Primer Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 80,
                "dependency_name" => "Coordinación Departamental de Chalatenango ",
                "address" => "Final calle San Martín y Av Libertad, Ex Cine Cayaguanca, ",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 81,
                "dependency_name" => "Coordinación Departamental de Ahuachapán ",
                "address" => "2a Av Nte, Nº 1-4 Barrio El Centro.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 82,
                "dependency_name" => "Dirección de Bienes Culturales Inmuebles y Gestión Urbana",
                "address" => "Final Calle México y 2a Av Sur, Barrio San Jacinto, Ex - Casa Presidencial, Segundo Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 83,
                "dependency_name" => "Parque Arqueológico Joya de Cerén",
                "address" => "Km. 35 Carretera a San Juan Opico",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 84,
                "dependency_name" => "Coordinación Departamental de Santa Ana",
                "address" => "2a Calle Pte. entre 6a y 8a Av Nte. No. 22.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 85,
                "dependency_name" => "Sitio Arqueológico Casa Blanca",
                "address" => "Km. 78, sobre la carretera de Santa Ana a Chalchuapa. ",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 86,
                "dependency_name" => "Centro Nacional de Artes - Dirección Nacional de Formación en Artes",
                "address" => "Calle Valero Lecha Edificio CENAR, Colonia San Mateo.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 87,
                "dependency_name" => "Subdirección de Bienes Culturales Inmuebles y Gestión Urbana",
                "address" => "Final Calle México y 2a Av Sur, Barrio San Jacinto, Ex - Casa Presidencial, Segundo Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 88,
                "dependency_name" => "Dirección General de Asuntos Jurídicos",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Segundo Nivel",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 89,
                "dependency_name" => "Dirección General de Comunicaciones Institucionales",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Tercer Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 90,
                "dependency_name" => "Dirección de Patrimonio Cultural Edificado",
                "address" => "Final Calle México y 10a Av. Sur, Barrio San Jacinto, Ex - Casa Presidencial, Segundo Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 91,
                "dependency_name" => "Dirección de Publicaciones e Impresos",
                "address" => "Dirección de Publicaciones e Impresos, 17 Av. Sur # 430,",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 92,
                "dependency_name" => "Dirección de Conservación de Bienes Culturales Muebles",
                "address" => "Av. La Revolución, Col. San Benito, Frente a CIFCO. Oficinas ubicadas en el Museo Nacional de Antropología Dr. David J. Guzmán",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 93,
                "dependency_name" => "Dirección General de Proyectos",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Tercer Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 94,
                "dependency_name" => "Dirección de Administración",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Tercer Nivel. ",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 95,
                "dependency_name" => "Dirección de Registro de Bienes Culturales Muebles",
                "address" => "Av. La Revolución, Col. San Benito, frente a CIFCO.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 96,
                "dependency_name" => "Biblioteca Pública  Prof. Saúl Flores",
                "address" => "Dr. Nicolás Peña No. 43, Barrio Candelaria, Zacatecoluca",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 97,
                "dependency_name" => "Dirección General de Relaciones Internacionales y Cooperación",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Tercer Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 98,
                "dependency_name" => "Dirección Nacional de Formación en Artes",
                "address" => "Calle Valero Lecha Edificio CENAR, Colonia San Mateo. ",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 99,
                "dependency_name" => "Dirección Nacional de Patrimonio Cultural",
                "address" => "Final Calle México y 10a Av. Sur, Barrio San Jacinto, Ex- Casa Presidencial, Segundo Nivel, ",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 100,
                "dependency_name" => "Dirección Nacional de Casas de la Cultura y Parques Culturales",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Segundo Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 101,
                "dependency_name" => "Dirección de Registro de Bienes Culturales de la Dirección Nacional de Patrimonio Cultural",
                "address" => "Av. La Revolución, Col. San Benito. Museo Nacional de Antropología Dr. David J. Guzmán",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 102,
                "dependency_name" => "Dirección Nacional de Artes",
                "address" => "75 Av. Sur, Pasaje C, Casa 4-B, Colonia Escalón.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 103,
                "dependency_name" => "Subdirección de Bienes Culturales Inmuebles y Gestión Urbana",
                "address" => "Final Calle México y 10a Av. Sur, Barrio San Jacinto, Ex- Casa Presidencial, Segundo Nivel,",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 104,
                "dependency_name" => "Dirección General Financiera Institucional",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Primer Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 105,
                "dependency_name" => "Dirección de Patrimonio Cultural Edificado ",
                "address" => "Final Calle México y 10a Av. Sur, Barrio San Jacinto, Ex- Casa Presidencial, Segundo Nivel,",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 106,
                "dependency_name" => "Dirección General de Género y Diversidad",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Tercer Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 107,
                "dependency_name" => "Dirección General de Planificación y Desarrollo Institucional",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Segundo Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 108,
                "dependency_name" => "Dirección General de Artes",
                "address" => "75 Av. Sur, Pasaje C, Casa 4 A, Colonia Escalón, ",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 109,
                "dependency_name" => "Dirección General de Proyectos de Inversión",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Tercer Nivel. ",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 110,
                "dependency_name" => "Dirección Financiera Institucional",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Primer Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 111,
                "dependency_name" => "Dirección de Espacios Culturales Públicos",
                "address" => "Final Calle México y 2a Av Sur, Barrio San Jacinto, Ex - Casa Presidencial, Segundo Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 112,
                "dependency_name" => "Dirección de Arqueología",
                "address" => "Av. La Revolución, Col. San Benito, frente a CIFCO. Oficinas ubicadas en el Museo Nacional de Antropología Dr. David J. Guzmán  ",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 113,
                "dependency_name" => "Dirección General de Investigaciones",
                "address" => "Avenida Cuscatlán y 2da. C. Pte. Centro Histórico.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 114,
                "dependency_name" => "Dirección de Cine",
                "address" => "Av. La Revolución, Col. San Benito. Museo Nacional de Antropología Dr. David J. Guzmán.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 115,
                "dependency_name" => "Dirección General de Comunicaciones Institucionales ",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Tercer Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 116,
                "dependency_name" => "Dirección de Bibliotecas Archivos y Publicaciones",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Tercer Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 117,
                "dependency_name" => "Centro Nacional de Artes - Dirección Nacional de Formación en Artes",
                "address" => "Calle Valero Lecha Edificio CENAR, Colonia San Mateo.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 118,
                "dependency_name" => "Dirección Nacional de Casas de la Cultura y Parques Culturales ",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Segundo Nivel",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 119,
                "dependency_name" => "Dirección de Arqueología de la Dirección Nacional de Patrimonio Cultural",
                "address" => "Av. La Revolución, Col. San Benito. Museo Nacional de Antropología Dr. David J. Guzmán",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 120,
                "dependency_name" => "Dirección Nacional de Archivos y Bibliotecas",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 121,
                "dependency_name" => "Dirección Nacional de Bibliotecas, Archivo y Publicaciones",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Segundo Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 122,
                "dependency_name" => "Dirección General de Administración",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Tercer Nivel. ",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 123,
                "dependency_name" => "Dirección General Ambiental",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Tercer Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 124,
                "dependency_name" => "Dirección General de Multiculturalidad",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Segundo Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 125,
                "dependency_name" => "Dirección de Planificación",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 126,
                "dependency_name" => "Dirección de Formación en Artes",
                "address" => "Calle Valero Lecha, Edificio CENAR, col. San Mateo.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 127,
                "dependency_name" => "Dirección Nacional de Formación en Artes ",
                "address" => "Calle Valero Lecha Edificio CENAR, Colonia San Mateo.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 128,
                "dependency_name" => "Dirección Nacional de Bibliotecas, Archivo y Publicaciones ",
                "address" => "Edificio Mercury 17 Av. Sur y Calle Rubén Darío #1003. ",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 129,
                "dependency_name" => "Dirección de Bienes Culturales Inmuebles y Gestión Urbana	",
                "address" => "Final Calle México y 10a Av. Sur, Barrio San Jacinto, Ex - Casa Presidencial, Segundo Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 130,
                "dependency_name" => "Dirección de Registro de Bienes Culturales",
                "address" => "Av. La Revolución, Col. San Benito. Museo Nacional de Antropología Dr. David J. Guzmán.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 131,
                "dependency_name" => "Dirección General de Asuntos Jurídicos ",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Segundo Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 132,
                "dependency_name" => "Dirección de Publicaciones e Impresos ",
                "address" => "17 Av. Sur Nº 430.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 133,
                "dependency_name" => "Dirección de Museos y Salas",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 134,
                "dependency_name" => "Dirección Nacional de Casas de la Cultura",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Segundo Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 135,
                "dependency_name" => "Dirección General de Investigaciones, Acervos Documentales y Ediciones",
                "address" => "Alam. Juan Pablo II y Calle Guadalupe, Plan Maestro, Centro de Gobierno, Edif. A-5, Tercer Nivel.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
            [
                "id" => 136,
                "dependency_name" => "Dirección General de Auditoría Interna",
                "address" => "Final Calle México y 2a Av Sur, Barrio San Jacinto, Ex - Casa Presidencial.",
                "superior_dependency" => "Guillermo Adalberto Jandres Escobar",
            ],
        ]);
    }
}
